engines:
  pylint:
    enabled: true
    channel: "beta"
    checks:
      unnecessary-pass:
        enabled: false
      invalid-name:
        enabled: false
      useless-super-delegation:
        enabled: false
      too-few-public-methods:
        enabled: false
      import-error:
        enabled: false
## other configuration excluded from example...
exclude_patterns:
  - "example/"

