apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: data-tools-apps
  description: Applications managed within the data-tools monorepo.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
