version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: master
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            sudo pip3 install --upgrade setuptools
      - run:
          name: run tests using setuptools
          command: |
            python3 setup.py test
  build_and_deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: setup virtual env
          command:  |
            python3 -m venv env
            source ./env/bin/activate
      - run:
          name: install python dependencies
          command: |
            sudo pip3 install --upgrade setuptools wheel twine
      - run:
          name: Build the distribution
          command: |
            export GIT_TAG=$(git describe --tags)
            echo "reading the latest version as $GIT_TAG"
            python3 setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            twine upload dist/*